port: 8000
federates:
  - https://spring83.kindrobot.ca
  - https://0l0.lol
  - https://bogbody.biz
  - https://spring83.mozz.us/
fqdn: localhost:8000
admin_board: bf71bb0d73bc3b0edfd0bd750f9e191c476773b3660d9ba86d658b49083e0623
