port: 8787
federates: []
fqdn: localhost:8000
admin_board: bf71bb0d73bc3b0edfd0bd750f9e191c476773b3660d9ba86d658b49083e0623
sql_driver: postgres
sql_connection_string: "user=springboard_test password=springboard_test dbname=springboard_test host=keyboard.local"
